FROM node:20-alpine AS build

WORKDIR /app

COPY FinWallet.Frontend/package*.json ./

RUN npm install

COPY FinWallet.Frontend/ .

RUN npm run build --configuration=production

FROM nginx:alpine

COPY --from=build /app/dist/FinWallet.Frontend/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]